### ISSUE TITLE
Error interacting with object store: Generic S3 error: Missing region

### ISSUE THREAD

**Issue by mvilrokx** [duckdb/duckdb_delta#14] opened 2024-05-24 19:55 UTC
I've create a very simple, small Delta Table on my minio instance. Whatever I do to query it, I get the following error:

```
IO Error: Hit DeltaKernel FFI error (from: get_default_client in DeltaScanScanBind): 
Hit error: 5 (GenericError) with message (Generic delta kernel error: Error interacting with object store: 
Generic S3 error: Missing region)
```

The table was created from the following parquet file (which is located in the same minio instance and I can query fine with duckdb):

```
D SELECT * FROM 's3://vilrokx/prices.parquet';
┌─────────┬─────────────────────┬───────┐
│ ticker  │        when         │ price │
│ varchar │      timestamp      │ int64 │
├─────────┼─────────────────────┼───────┤
│ APPL    │ 2001-01-01 00:00:00 │     1 │
│ APPL    │ 2001-01-01 00:01:00 │     2 │
│ APPL    │ 2001-01-01 00:02:00 │     3 │
│ MSFT    │ 2001-01-01 00:00:00 │     1 │
│ MSFT    │ 2001-01-01 00:01:00 │     2 │
│ MSFT    │ 2001-01-01 00:02:00 │     3 │
│ GOOG    │ 2001-01-01 00:00:00 │     1 │
│ GOOG    │ 2001-01-01 00:01:00 │     2 │
│ GOOG    │ 2001-01-01 00:02:00 │     3 │
└─────────┴─────────────────────┴───────┘
```

Tried:
```
D SET s3_endpoint='127.0.0.1:9000';
D SET s3_use_ssl=false;
D SET s3_url_style='path';
D SET s3_region='us-east-1';
D SELECT * FROM delta_scan('s3://delta-lake/prices_table');
IO Error: Hit DeltaKernel FFI error (from: get_default_client in DeltaScanScanBind): Hit error: 5 (GenericError) with message (Generic delta kernel error: Error interacting with object store: Generic S3 error: Missing region)
D SELECT ticker FROM delta_scan('s3://delta-lake/prices_table');
IO Error: Hit DeltaKernel FFI error (from: get_default_client in DeltaScanScanBind): Hit error: 5 (GenericError) with message (Generic delta kernel error: Error interacting with object store: Generic S3 error: Missing region)
```

I am setting the region, as you can see, even though this should not be needed for a local Minio instance I would assume.

When I do the same with a Delta table on my local file system I get a different error:

```
D SELECT * FROM delta_scan('file:///prices_table') limit 1;
IO Error: Hit DeltaKernel FFI error (from: snapshot in DeltaScanScanBind): Hit error: 15 (MissingVersionError) with message (No table version found.)
```

**Comment by mvilrokx** [comment] 2024-05-24 21:53
FYI, this works perfectly fine on the same Delta Table:

```python
from deltalake import DeltaTable

table_path = "prices_table"

df = DeltaTable(table_path).to_pandas()

print(df)
```

**Comment by marsupialtail** [comment] 2024-05-25 18:30
try this: CREATE SECRET (TYPE S3, provider credential_chain);

**Comment by samansmink** [comment] 2024-05-28 08:46
Yea the delta extension only works with DuckDB's [secrets](https://duckdb.org/docs/configuration/secrets_manager.html). So if you have a non-default region you will need to create an S3 secret with the correct region. @marsupialtail's solution will work if you have an s3 config in a standard location with your region, otherwise you can use:

```SQL
CREATE SECRET (
    TYPE S3,
    REGION 'my-region'
);
FROM delta_scan('....');
```

**Comment by mvilrokx** [comment] 2024-05-28 16:30
What about all the other settings?

```
D SET s3_endpoint='127.0.0.1:9000';
D SET s3_use_ssl=false;
D SET s3_url_style='path';
```

When I set the secret, as per @samansmink's comment, I get:

```
IO Error: Hit DeltaKernel FFI error (from: snapshot in DeltaScanScanBind): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic S3 error: Error after 10 retries in 2.227643s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://s3.my-region.amazonaws.com/delta-lake/prices_table/_delta_log/_last_checkpoint): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known)
```

which seems to suggest that it is not picking up the `s3_endpoint` I `SET`.

**Comment by samansmink** [comment] 2024-05-29 08:39
Yea no not yet, I'm only passing region and credentials atm, the rest should be easy to add (see [src](https://github.com/duckdb/duckdb_delta/blob/b0acfc02d04b1e378f88a5289a0e103d1f33e989/src/functions/delta_scan.cpp#L115))

I will try to get to this soonish

**Comment by mvilrokx** [comment] 2024-05-29 15:47
> Yea no not yet, I'm only passing region and credentials atm, the rest should be easy to add (see [src](https://github.com/duckdb/duckdb_delta/blob/b0acfc02d04b1e378f88a5289a0e103d1f33e989/src/functions/delta_scan.cpp#L115))

Yeah that would be needed if you want to support e.g. minio

**Comment by astrojuanlu** [comment] 2024-06-29 16:02
Came here to say that endpoints are being ignored, hence Delta on Minio is not supported yet.

```sql
INSTALL httpfs;
LOAD httpfs;

INSTALL delta;
LOAD delta;

CREATE SECRET secret_minio (
    TYPE S3,
    ENDPOINT 'localhost:9000',
    URL_STYLE 'path',
    USE_SSL false,
    KEY_ID 'minioadmin',
    SECRET 'minioadmin'
);

SELECT * FROM read_parquet("s3://test/submissions.pq");  # Works
SELECT * FROM delta_scan('s3://reddit-submissions/submissions-raw');  # Doesn't even hit http://localhost:9000
```

**Comment by rmoff** [comment] 2024-07-10 19:05
I'm seeing the same issue (DuckDB v1.0.0 1f98600c2c)

Set the MinIO config as a secret: 

```sql
🟡◗ CREATE SECRET secret1 (
      TYPE S3,
      KEY_ID 'admin',
      SECRET 'password',
      REGION 'us-east-1',
      ENDPOINT 'minio:9000',
      URL_STYLE 'path',
      USE_SSL 'false'

  );
```

Confirm that DuckDB can read from MinIO: 

```sql
🟡◗ select * from 's3://warehouse/part-85ca931a-7502-4736-964b-6b6127d7547a-0.snappy.parquet' 
UNION ALL 
select * from 's3://warehouse/part-c575067f-bb5c-471a-a344-45efe7dead2b-0.snappy.parquet';
┌─────────┬───────┐
│   c1    │  c2   │
│ varchar │ int32 │
├─────────┼───────┤
│ a       │    42 │
│ a       │    42 │
└─────────┴───────┘
Run Time (s): real 0.031 user 0.009555 sys 0.002291
```

Try to read the Delta table: 

```sql
🟡◗ SELECT * FROM delta_scan('s3://warehouse/');
IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 's3://warehouse/'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic S3 error: Received redirect without LOCATION, this normally indicates an incorrectly configured region)
```

Confirm that the Delta table is valid, by copying it to local filesystem and then reading it locally: 

```sql
🟡◗ SELECT * FROM delta_scan('/Users/rmoff/warehouse/');
┌─────────┬───────┐
│   c1    │  c2   │
│ varchar │ int32 │
├─────────┼───────┤
│ a       │    42 │
│ a       │    42 │
└─────────┴───────┘
Run Time (s): real 0.061 user 0.152989 sys 0.081464
```

**Comment by qchappat** [comment] 2024-10-15 18:56
Hey @mvilrokx. 

I am taking the liberty to restart discussion on this issue because I am facing the same problem. 

I am trying to access a Delta Lake table located on a private AWS S3 bucket. It works well when I load it using Delta Lake (delta-rs) package and then use PyArrow to read it to DuckDB (using DuckDB's Python client). But when I use this Delta - DuckDB integration, I face this error: 

`Error interacting with object store: Generic S3 error: Received redirect without LOCATION, this normally indicates an incorrectly configured region. `

I tried setting all the types of secret possible (all combinations of REGION, CREDENTIAL_PROVIDER, and different CHAIN) but nothing works. While for the delta-rs package, I just call using the path and storage_options. Like this

```
storage_options = {
    "region": AWS_REGION,
}
dt = DeltaTable(path, storage_options=storage_options)
```

@mvilrokx I was wondering if you found a way to solve your region error.

@samansmink do you have any suggestions on what I should do to make it work? 

Thank you very much in advance for your time and help. I appreciate it a lot!

Best,
Quentin

**Comment by samansmink** [comment] 2024-11-14 16:36
sorry for missing this one @qchappat, would you mind trying again with latest release of delta and opening a new issue if this issue persists?

I will close this issue for now since a lot was changed in the meantime

**Closed by samansmink** 2024-11-14 16:36 UTC

**Comment by qchappat** [comment] 2024-11-14 22:22
Thank you @samansmink, it seems the issue is solved now! Thanks a lot for updating me!
